name: Build and release

on:
    push:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to Github packages
                uses: docker/login-action@v1
                with:
                    username: duncte123
                    password: ${{ secrets.DOCKER_TOKEN }}

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: duncte123/ghostbot:latest
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

            -   name: Trigger dev webhook
                uses: distributhor/workflow-webhook@v3
                env:
                    webhook_url: ${{ secrets.WEBHOOK_URL }}
